#!/usr/bin/env python3
"""Generate xschem/openlayout_theme.tcl (colors + Tk widget styling) from share/theme/openlayout.json."""
import json
from pathlib import Path

FLOW = Path(__file__).resolve().parents[2]
theme = json.loads((FLOW / "share/theme/openlayout.json").read_text())
ui, font, layers = theme["ui"], theme["font"], theme["schematic"]["layers"]
assert len(layers) == 22, "xschem expects 22 layer colors"

rows = "\n".join("  " + " ".join(f'"{c}"' for c in layers[i:i + 5]) for i in range(0, 22, 5))
options = {
    "*Background": ui["panel"], "*Foreground": ui["text"],
    "*activeBackground": ui["border"], "*activeForeground": ui["text"],
    "*selectBackground": ui["select"], "*selectForeground": "#ffffff",
    "*highlightBackground": ui["panel"], "*highlightColor": ui["accent"],
    "*troughColor": ui["base"], "*insertBackground": ui["text"],
    "*disabledForeground": ui["dim"], "*selectColor": ui["base"],
    "*Entry.Background": ui["base"], "*Text.Background": ui["base"],
    "*Listbox.Background": ui["base"], "*Spinbox.Background": ui["base"],
    "*Menu.Background": ui["panel"], "*Menu.activeBackground": ui["select"],
    "*Menu.activeForeground": "#ffffff", "*Menu.relief": "flat",
    "*Button.relief": "flat", "*Menubutton.relief": "flat",
}
lines = [
    "# Generated by share/theme/gen_xschem_theme.py from share/theme/openlayout.json - do not edit.",
    "set dark_colorscheme 1",
    "set cadlayers 22",
    f"set dark_colors {{\n{rows}}}",
    f"set ol_theme(ui) {{{' '.join(f'{k} {v}' for k, v in ui.items())}}}",
    f'set ol_theme(font) {{{{{font["ui"]}}} {font["ui_size"]}}}',
    f'set ol_theme(mono) {{{{{font["mono"]}}} {font["mono_size"]}}}',
]
# Widget styling only when Tk is loaded (xschem -x netlisting runs without a display).
lines += ['if {[info commands option] ne ""} {']
lines += [f"  option add {k} {v} widgetDefault" for k, v in options.items()]
lines += ['  option add *Font $ol_theme(font) widgetDefault',
          '  option add *Text.Font $ol_theme(mono) widgetDefault', '}']
out = FLOW / "xschem/openlayout_theme.tcl"
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out}")
