#!/usr/bin/env python3
"""Generate xschem/openlayout_theme.tcl (colors + Tk widget styling) from share/theme/openlayout.json."""
import json
from pathlib import Path

FLOW = Path(__file__).resolve().parents[2]
theme = json.loads((FLOW / "share/theme/openlayout.json").read_text())
ui, font, canvas, layers = theme["ui"], theme["font"], theme["canvas"], theme["schematic"]["layers"]
assert len(layers) == 22, "xschem expects 22 layer colors"


def blend(a, b, t):
    """color a blended towards b by t"""
    ca, cb = (tuple(int(c[i:i + 2], 16) for i in (1, 3, 5)) for c in (a, b))
    return "#" + "".join(f"{round(x + (y - x) * t):02x}" for x, y in zip(ca, cb))


menu_bg = blend(ui["panel"], ui["border"], 0.5)   # drop-down menus: a step off the toolbar under them

rows = "\n".join("  " + " ".join(f'"{c}"' for c in layers[i:i + 5]) for i in range(0, 22, 5))
# Tk option database. xschem sets its own grey palette with the same patterns (*background, ...) at
# startupFile priority and the selection colors at interactive priority: these go in at interactive
# priority, after xschem's (ol_theme_options is called again once xschem's GUI is set up), so every
# widget xschem creates later - dialogs, the symbol chooser, property forms - is themed too.
options = {
    # every widget
    "*background": ui["panel"], "*foreground": ui["text"],
    "*activeBackground": ui["border"], "*activeForeground": ui["text"],
    "*disabledForeground": ui["dim"], "*disabledBackground": ui["panel"],
    "*readonlyBackground": ui["alt"],
    "*selectBackground": ui["select"], "*selectForeground": "#ffffff",
    "*inactiveSelectBackground": ui["border"],
    "*highlightBackground": ui["panel"], "*highlightColor": ui["accent"], "*highlightThickness": 0,
    "*troughColor": ui["base"], "*insertBackground": ui["text"], "*selectColor": ui["base"],
    # inputs and lists: the darker base, flat, a thin accent ring when focused
    "*Entry.background": ui["base"], "*Entry.relief": "flat", "*Entry.borderWidth": 3,
    "*Entry.highlightThickness": 1, "*Entry.highlightBackground": ui["border"],
    "*Spinbox.background": ui["base"], "*Spinbox.relief": "flat", "*Spinbox.buttonBackground": ui["border"],
    "*Text.background": ui["base"], "*Text.relief": "flat", "*Text.borderWidth": 6,
    "*Listbox.background": ui["base"], "*Listbox.relief": "flat", "*Listbox.borderWidth": 0,
    "*Listbox.activeStyle": "none",
    # buttons: flat, a little lighter than the panel, the selection blue under the mouse
    "*Button.background": ui["border"], "*Button.activeBackground": ui["select"],
    "*Button.activeForeground": "#ffffff", "*Button.relief": "flat", "*Button.borderWidth": 0,
    "*Button.padX": 10, "*Button.padY": 3,
    "*Menubutton.relief": "flat", "*Menubutton.activeBackground": ui["select"],
    "*Checkbutton.activeBackground": ui["panel"], "*Radiobutton.activeBackground": ui["panel"],
    # menus: padded panel, the selection blue on the active entry
    "*Menu.background": menu_bg, "*Menu.activeBackground": ui["select"],
    "*Menu.activeForeground": "#ffffff", "*Menu.relief": "flat", "*Menu.borderWidth": 5,
    "*Menu.activeBorderWidth": 0, "*Menu.selectColor": ui["accent"],
    # scrollbars and panes: thin and flat
    "*Scrollbar.background": ui["border"], "*Scrollbar.activeBackground": ui["dim"],
    "*Scrollbar.troughColor": ui["base"], "*Scrollbar.relief": "flat", "*Scrollbar.borderWidth": 0,
    "*Scrollbar.elementBorderWidth": 0, "*Scrollbar.width": 10,
    "*Panedwindow.sashRelief": "flat", "*Panedwindow.sashWidth": 4, "*Panedwindow.background": ui["window"],
    "*Labelframe.foreground": ui["dim"],
}
lines = [
    "# Generated by share/theme/gen_xschem_theme.py from share/theme/openlayout.json - do not edit.",
    "set dark_colorscheme 1",
    "set dark_gui_colorscheme 1",
    "set cadlayers 22",
    f"set dark_colors {{\n{rows}}}",
    f"set ol_theme(ui) {{{' '.join(f'{k} {v}' for k, v in ui.items())}}}",
    f"set ol_theme(canvas) {{{' '.join(f'{k} {v}' for k, v in canvas.items())}}}",
    f"set ol_theme(menu) {menu_bg}",
    f'set ol_theme(font) {{{{{font["ui"]}}} {font["ui_size"]}}}',
    f'set ol_theme(mono) {{{{{font["mono"]}}} {font["mono_size"]}}}',
    "",
    "# Widget styling (Tk option database); a no-op without Tk (xschem -x netlisting runs without a display).",
    "proc ol_theme_options {} {",
    "  global ol_theme",
    '  if {[info commands option] eq ""} { return }',
]
lines += [f"  option add {k} {v} interactive" for k, v in options.items()]
lines += [
    "  option add *font $ol_theme(font) interactive",
    "  option add *Text.font $ol_theme(mono) interactive",
    "  option add *Entry.font $ol_theme(font) interactive",
    "  # ttk widgets (xschem's comboboxes)",
    '  if {[info commands ttk::style] ne ""} {',
    f'    ttk::style configure TCombobox -fieldbackground {ui["base"]} -background {ui["border"]} '
    f'-foreground {ui["text"]} -arrowcolor {ui["text"]} -bordercolor {ui["border"]} -lightcolor {ui["base"]} '
    f'-darkcolor {ui["base"]} -selectbackground {ui["select"]} -selectforeground #ffffff',
    f'    ttk::style map TCombobox -fieldbackground {{readonly {ui["base"]}}} -foreground {{readonly {ui["text"]}}}',
    "  }",
    "}",
    "ol_theme_options",
]
out = FLOW / "xschem/openlayout_theme.tcl"
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out}")
