# Generated by share/theme/gen_xschem_theme.py from share/theme/openlayout.json - do not edit.
set dark_colorscheme 1
set cadlayers 22
set dark_colors {
  "#0e1014" "#5fb4ff" "#8a93a6" "#d9dee7" "#4cc38a"
  "#ef6b6b" "#4fa3ff" "#ef6b6b" "#e8b04b" "#ffffff"
  "#c678dd" "#7bd88f" "#3d7bd9" "#b5a642" "#9fb7a5"
  "#ff8a80" "#bfff81" "#4dd0c4" "#d16ba5" "#d2d46b"
  "#ef6158" "#fdb200"}
set ol_theme(ui) {window #1f2329 panel #262b33 base #181b20 alt #1d2127 border #323843 text #d9dee7 dim #7d8696 accent #4fa3ff select #2c5d94 ok #4cc38a fail #ef6b6b warn #e8b04b}
set ol_theme(font) {{DejaVu Sans} 10}
set ol_theme(mono) {{DejaVu Sans Mono} 10}
if {[info commands option] ne ""} {
  option add *Background #262b33 widgetDefault
  option add *Foreground #d9dee7 widgetDefault
  option add *activeBackground #323843 widgetDefault
  option add *activeForeground #d9dee7 widgetDefault
  option add *selectBackground #2c5d94 widgetDefault
  option add *selectForeground #ffffff widgetDefault
  option add *highlightBackground #262b33 widgetDefault
  option add *highlightColor #4fa3ff widgetDefault
  option add *troughColor #181b20 widgetDefault
  option add *insertBackground #d9dee7 widgetDefault
  option add *disabledForeground #7d8696 widgetDefault
  option add *selectColor #181b20 widgetDefault
  option add *Entry.Background #181b20 widgetDefault
  option add *Text.Background #181b20 widgetDefault
  option add *Listbox.Background #181b20 widgetDefault
  option add *Spinbox.Background #181b20 widgetDefault
  option add *Menu.Background #262b33 widgetDefault
  option add *Menu.activeBackground #2c5d94 widgetDefault
  option add *Menu.activeForeground #ffffff widgetDefault
  option add *Menu.relief flat widgetDefault
  option add *Button.relief flat widgetDefault
  option add *Menubutton.relief flat widgetDefault
  option add *Font $ol_theme(font) widgetDefault
  option add *Text.Font $ol_theme(mono) widgetDefault
}
