# Generated by share/theme/gen_xschem_theme.py from share/theme/openlayout.json - do not edit.
set dark_colorscheme 1
set dark_gui_colorscheme 1
set cadlayers 22
set dark_colors {
  "#0e1014" "#5fb4ff" "#8a93a6" "#d9dee7" "#4cc38a"
  "#ef6b6b" "#4fa3ff" "#ef6b6b" "#e8b04b" "#ffffff"
  "#c678dd" "#7bd88f" "#3d7bd9" "#b5a642" "#9fb7a5"
  "#ff8a80" "#bfff81" "#4dd0c4" "#d16ba5" "#d2d46b"
  "#ef6158" "#fdb200"}
set ol_theme(ui) {window #1f2329 panel #262b33 base #181b20 alt #1d2127 border #323843 text #d9dee7 dim #7d8696 accent #4fa3ff select #2c5d94 ok #4cc38a fail #ef6b6b warn #e8b04b}
set ol_theme(canvas) {background #0e1014 grid #3a4150 axis #7d8696 selection #ffffff text #d9dee7 cursor #e8b04b ruler #ffa31a cell_box #7d8696}
set ol_theme(menu) #2c323b
set ol_theme(font) {{DejaVu Sans} 10}
set ol_theme(mono) {{DejaVu Sans Mono} 10}

# Widget styling (Tk option database); a no-op without Tk (xschem -x netlisting runs without a display).
proc ol_theme_options {} {
  global ol_theme
  if {[info commands option] eq ""} { return }
  option add *background #262b33 interactive
  option add *foreground #d9dee7 interactive
  option add *activeBackground #323843 interactive
  option add *activeForeground #d9dee7 interactive
  option add *disabledForeground #7d8696 interactive
  option add *disabledBackground #262b33 interactive
  option add *readonlyBackground #1d2127 interactive
  option add *selectBackground #2c5d94 interactive
  option add *selectForeground #ffffff interactive
  option add *inactiveSelectBackground #323843 interactive
  option add *highlightBackground #262b33 interactive
  option add *highlightColor #4fa3ff interactive
  option add *highlightThickness 0 interactive
  option add *troughColor #181b20 interactive
  option add *insertBackground #d9dee7 interactive
  option add *selectColor #181b20 interactive
  option add *Entry.background #181b20 interactive
  option add *Entry.relief flat interactive
  option add *Entry.borderWidth 3 interactive
  option add *Entry.highlightThickness 1 interactive
  option add *Entry.highlightBackground #323843 interactive
  option add *Spinbox.background #181b20 interactive
  option add *Spinbox.relief flat interactive
  option add *Spinbox.buttonBackground #323843 interactive
  option add *Text.background #181b20 interactive
  option add *Text.relief flat interactive
  option add *Text.borderWidth 6 interactive
  option add *Listbox.background #181b20 interactive
  option add *Listbox.relief flat interactive
  option add *Listbox.borderWidth 0 interactive
  option add *Listbox.activeStyle none interactive
  option add *Button.background #323843 interactive
  option add *Button.activeBackground #2c5d94 interactive
  option add *Button.activeForeground #ffffff interactive
  option add *Button.relief flat interactive
  option add *Button.borderWidth 0 interactive
  option add *Button.padX 10 interactive
  option add *Button.padY 3 interactive
  option add *Menubutton.relief flat interactive
  option add *Menubutton.activeBackground #2c5d94 interactive
  option add *Checkbutton.activeBackground #262b33 interactive
  option add *Radiobutton.activeBackground #262b33 interactive
  option add *Menu.background #2c323b interactive
  option add *Menu.activeBackground #2c5d94 interactive
  option add *Menu.activeForeground #ffffff interactive
  option add *Menu.relief flat interactive
  option add *Menu.borderWidth 5 interactive
  option add *Menu.activeBorderWidth 0 interactive
  option add *Menu.selectColor #4fa3ff interactive
  option add *Scrollbar.background #323843 interactive
  option add *Scrollbar.activeBackground #7d8696 interactive
  option add *Scrollbar.troughColor #181b20 interactive
  option add *Scrollbar.relief flat interactive
  option add *Scrollbar.borderWidth 0 interactive
  option add *Scrollbar.elementBorderWidth 0 interactive
  option add *Scrollbar.width 10 interactive
  option add *Panedwindow.sashRelief flat interactive
  option add *Panedwindow.sashWidth 4 interactive
  option add *Panedwindow.background #1f2329 interactive
  option add *Labelframe.foreground #7d8696 interactive
  option add *font $ol_theme(font) interactive
  option add *Text.font $ol_theme(mono) interactive
  option add *Entry.font $ol_theme(font) interactive
  # ttk widgets (xschem's comboboxes)
  if {[info commands ttk::style] ne ""} {
    ttk::style configure TCombobox -fieldbackground #181b20 -background #323843 -foreground #d9dee7 -arrowcolor #d9dee7 -bordercolor #323843 -lightcolor #181b20 -darkcolor #181b20 -selectbackground #2c5d94 -selectforeground #ffffff
    ttk::style map TCombobox -fieldbackground {readonly #181b20} -foreground {readonly #d9dee7}
  }
}
ol_theme_options
